// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2CwQ5fltc7W1SyQbXnru5ISQ_ktRVss4',
    appId: '1:760470281140:web:18ff7e9f47953ffe8b30e1',
    messagingSenderId: '760470281140',
    projectId: 'deneme-c8433',
    authDomain: 'deneme-c8433.firebaseapp.com',
    storageBucket: 'deneme-c8433.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAounI3G2l0ZUM2RNquhF9GZStzNBPUFJY',
    appId: '1:760470281140:android:0448a8adb8f418e48b30e1',
    messagingSenderId: '760470281140',
    projectId: 'deneme-c8433',
    storageBucket: 'deneme-c8433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbjeAt14U43BUexeCccGYQYS0Uto53iQ',
    appId: '1:760470281140:ios:b29d47981c31e4e78b30e1',
    messagingSenderId: '760470281140',
    projectId: 'deneme-c8433',
    storageBucket: 'deneme-c8433.firebasestorage.app',
    iosBundleId: 'com.example.ozcanProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXbjeAt14U43BUexeCccGYQYS0Uto53iQ',
    appId: '1:760470281140:ios:b29d47981c31e4e78b30e1',
    messagingSenderId: '760470281140',
    projectId: 'deneme-c8433',
    storageBucket: 'deneme-c8433.firebasestorage.app',
    iosBundleId: 'com.example.ozcanProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2CwQ5fltc7W1SyQbXnru5ISQ_ktRVss4',
    appId: '1:760470281140:web:9c7b9d9122f86ec18b30e1',
    messagingSenderId: '760470281140',
    projectId: 'deneme-c8433',
    authDomain: 'deneme-c8433.firebaseapp.com',
    storageBucket: 'deneme-c8433.firebasestorage.app',
  );
}
